branches:
  - main
  # TODO: Remove this before merging the branch
  - 171-add-semantic-release
plugins:
  - "semantic-release-unsquash"
  -
    - "@semantic-release/npm"
    - pkgRoot: "./dist/tech-carbon-estimator"
      tarballDir: "./dist/tech-carbon-estimator"
  - "@semantic-release/github"
# TODO: Remove this before merging the branch
debug: true
