name: 'Run Playwright'
description: 'Sets up Python, installs dependencies and runs playwright tests'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'
    - name: Install Playwright Dependencies
      run: npm run playwright-install
      shell: bash
    - name: Run Playwright tests
      run: npm run playwright-test
      shell: bash
