name: 'Run Playwright'
description: 'Installs dependencies and runs playwright tests'
runs:
  using: 'composite'
  steps:
    # - name: Setup Python
    #   uses: actions/setup-python@v5.1.0
    #   with:
    #     python-version: '3.11'
    - name: Install Playwright Dependencies
      run: npm run playwright-install
      shell: bash
    - name: Run Playwright tests
      run: npm run playwright-test -- --trace=retain-on-failure
      shell: bash
    - name: Upload Playwright traces and report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces-and-report
        path: |
          test-results/
          playwright-report/
