name: 'Set up environment'
description: 'Sets up Node and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.18
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
      shell: bash
