name: Build and Test
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/set-up-environment
      - name: Build app
        run: npm run build
  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/set-up-environment
      - name: Run tests
        run: npm test
  playwright_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/set-up-environment
      - name: Run Playwright
        uses: ./.github/actions/run-playwright
