name: Deploy estimator Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/buildAndTest.yml

  publish_pages:
    needs: build_and_test
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/shared-pages.yml
