name: Playwright Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up environment
      uses: ./.github/actions/set-up-environment
    - name: Run Playwright
      uses: ./.github/actions/run-playwright
