name: Update Playwright Screenshots
on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: false
        default: 'Auto-commit: Update screenshots'
permissions:
  contents: write

jobs:
  playwright_screenshots:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up environment
        uses: ./.github/actions/set-up-environment
        
      - name: Run Playwright
        uses: ./.github/actions/update-playwright-screenshots
        
      - name: Check for changes
        id: changes
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
         
      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        shell: bash
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "${{ github.event.inputs.commit_message || 'Auto-commit: Update screenshots' }} (by @${{ github.actor }})"
          git push